spring:
  application:
    name: SouvenirStoreProject

  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/souvenir-store}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /souvenir